"""add question cache table

Revision ID: 0c2a55196561
Revises: cf790fa073c4
Create Date: 2026-09-07 23:11:01.497037

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c2a55196561'
down_revision: Union[str, Sequence[str], None] = 'cf790fa073c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('question_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.String(length=20), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('sources', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['video_id'], ['videos.video_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('video_id', 'question', name='uq_question_cache_video_question')
    )
    op.create_index(op.f('ix_question_cache_id'), 'question_cache', ['id'], unique=False)
    op.create_index(op.f('ix_question_cache_video_id'), 'question_cache', ['video_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_question_cache_video_id'), table_name='question_cache')
    op.drop_index(op.f('ix_question_cache_id'), table_name='question_cache')
    op.drop_table('question_cache')
    # ### end Alembic commands ###
